# Generated by Django 2.2.7 on 2021-12-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Foydalanuvchining Telegram ID raqami')),
                ('name', models.CharField(max_length=15, verbose_name='Foydalanuvchi ismi')),
                ('surname', models.CharField(max_length=15, verbose_name='Foydalanuvchi familyasi')),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('TR', 'Teacher'), ('ST', 'Student')], default='ST', max_length=7)),
                ('semestr', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=0)),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.Area', verbose_name="Yo'nalish")),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.Faculty', verbose_name='Fakultet')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.Faculty'),
        ),
    ]
