# Generated by Django 2.2.7 on 2021-12-06 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nomi')),
                ('semestr', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_list', models.CharField(max_length=100, verbose_name="Mavzular ro'yxati")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.Subjects')),
            ],
            options={
                'verbose_name': "Mavzular ro'yxati",
                'verbose_name_plural': "Mavzular ro'yxati jadvali",
            },
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('ppt_file', models.CharField(max_length=100, verbose_name='Taqdimot manzili')),
                ('word_file', models.CharField(max_length=100, verbose_name='Laboratoriya manzili')),
                ('video', models.CharField(max_length=100, verbose_name='Video manzili')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.Themes')),
            ],
            options={
                'verbose_name': 'Laboratoriya',
                'verbose_name_plural': 'Laboratoriyalar',
            },
        ),
    ]
