# Generated by Django 2.2.7 on 2021-12-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20211206_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
