# Generated by Django 2.2.7 on 2021-12-05 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_auto_20211204_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=13, verbose_name='Telefon raqam'),
            preserve_default=False,
        ),
    ]
