# Generated by Django 2.2.7 on 2021-12-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_auto_20211207_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratories',
            name='theme',
        ),
        migrations.AddField(
            model_name='laboratories',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ugc.Subjects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='themes_list',
            field=models.CharField(default=1, max_length=100, verbose_name="Mavzular ro'yxati"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Themes',
        ),
    ]
