# Generated by Django 2.2.7 on 2021-12-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_laboratories_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ugc.Area'),
            preserve_default=False,
        ),
    ]
