# Generated by Django 2.2.7 on 2021-12-08 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ugc', '0007_subjects_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('ppt_file', models.CharField(max_length=100, verbose_name='Taqdimot manzili')),
                ('word_file', models.CharField(max_length=100, verbose_name='Laboratoriya manzili')),
                ('video', models.CharField(max_length=100, verbose_name='Video manzili')),
                ('other_file', models.CharField(max_length=100, verbose_name="Qo'shimcha Fayl manzili")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.Subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ma'ruza",
                'verbose_name_plural': "Ma'ruzalar",
            },
        ),
    ]
