# Generated by Django 3.2.9 on 2021-12-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_lectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='themes_list',
            field=models.FileField(upload_to='theme_list/', verbose_name="Mavzular ro'yxati"),
        ),
    ]
